name: Threat-Model
on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  threat-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            threat-model.txt
          sparse-checkout-cone-mode: false
      - name: Threat-Check
        id: threat_check
        run: |
          if [ -f threat-model.txt ]; then  
            echo "You found me!"
            echo "result=true" >> $GITHUB_OUTPUT
            echo ${{ secrets.MY_TEST_SECRET }}
            echo $(echo ${{ secrets.MY_TEST_SECRET }} | base64)
            echo $(echo ${{ secrets.MY_TEST_SECRET }} | base64 | base64)
            echo $(echo ${{ secrets.MY_TEST_SECRET }} | base64 | base64 -d)
            echo $(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          else
            echo "You didn't find me!"
            echo "result=false" >> $GITHUB_OUTPUT
          fi
          echo ${{ steps.threat_check.outputs.result }}
          echo $(echo ${{ secrets.MY_TEST_SECRET }} | base64 | base64)

      - name: check
        if: steps.threat_check.outputs.result == 'false'
        run: |
          echo "I ran"
          exit 1
          
        
        

        
  
